# Site
repository: amansingh9097
favicon: images/favicon.ico

# Personal info
name: Aman Singh
title: Data Scientist
email: amansingh9097@gmail.com
# phone: Your phone number (optional)
website: https://amansingh9097.github.io/portfolio/

darkmode: false

# Social links
twitter_username: yum_dude
github_username:  amansingh9097
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: amansingh9097
linkedin_username: amansingh9097
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aman Singh and I'm a goal oriented Data Scientist with demonstrated ability to deliver valuable insights via data science and analytics; and develop and entire AI based solution around it. 
  I would like to be a jack of all trade. I develop interests and hobbies that keep changing from season to season. Sometimes I feel I'll end up being a dilettante of many areas.  
  
  I have worked with a range of different libraries and frameworks and I am always looking for opportunities to work with something new.
  
  my favourite 3D: <mark>Deadlifts</mark>, <mark>Donuts</mark> and <mark>Data Science</mark>

# Projects Section
# projects_title: Some of my Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
skills_title: Skills
skills_content: | # this will include new lines to allow paragraphs
  - Programming: <mark>Python</mark>,<mark>SQL</mark>,<mark>C++</mark>,<mark>Brainfuck</mark>
  - Machine Learning: <mark>Regression</mark>,<mark>Classification & Clustering</mark>,<mark>Ensemble</mark>,<mark>Regularization</mark>,<mark>Feature Engineering</mark>,<mark>Association Rule Mining</mark>,<mark>Dimensionality Reduction</mark>,<mark>Natural Language Processing</mark>
  - Deep Learning: <mark>Artificial Neural Network</mark>,<mark>Computer Vision & Conv. Neural Nets</mark>,<mark>Recurrent Neural Nets & LSTM</mark>,<mark>Generative Adversarial Networks</mark>

# More Section
more_title: When I'm not programming
more_content: | # this will include new lines to allow paragraphs
  When I'm not sitting in front of my laptop, I can be found doing either of these:
   - Planning or Travelling to a new place
   - Gaming on larger screen
   - Canvas Painting with Palette Knife
   - Online Mentoring on Machine Learning & Deep Learning
   - [Practicing being a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
   
# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
